parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\BehaviorBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\BehaviorBundle\EventListener\SoftDeleteListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: duo.behavior.event.onDelete, method: onDelete }
            - { name: kernel.event_listener, event: duo.behavior.event.onUndelete, method: onUndelete }

    Duo\BehaviorBundle\EventListener\VersionListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: duo.behavior.event.onClone, method: onClone }
            - { name: kernel.event_listener, event: duo.behavior.event.onRevert, method: onRevert }

    Duo\BehaviorBundle\EventSubscriber\PublishSubscriber:
        arguments:
            $tokenHelper: '@Duo\SecurityBundle\Helper\TokenHelper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\BehaviorBundle\EventSubscriber\SlugSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: 16 }

    Duo\BehaviorBundle\EventSubscriber\SoftDeleteSubscriber:
        arguments:
            $tokenHelper: '@Duo\SecurityBundle\Helper\TokenHelper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\BehaviorBundle\EventSubscriber\SortSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\BehaviorBundle\EventSubscriber\TimeStampSubscriber:
        arguments:
            $tokenHelper: '@Duo\SecurityBundle\Helper\TokenHelper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\BehaviorBundle\EventSubscriber\TranslateSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\BehaviorBundle\EventSubscriber\TreeSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\BehaviorBundle\EventSubscriber\UrlSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: 8 }

    Duo\BehaviorBundle\EventSubscriber\VersionSubscriber:
        tags:
            - { name: doctrine.event_subscriber }