pages:

media:
    label: Media
    url: javascript:; #/admin/media

forms:

security:

modules:

seo:

settings:
    label: Settings
    children:
        translations:
            label: Translations
            url: javascript:; #/admin/setting/translation