content:
    label: duo_admin.menu.content
    icon: icon-display
    children:
        pages:
            label: duo_page.menu.pages
            route: duo_page_listing_page_index
            icon: icon-files-empty
        menu:
            label: duo_page.menu.page_tree
            route: duo_page_listing_page_tree_index
            icon: icon-tree
        media:
            label: duo_media.menu.media
            route: duo_media_listing_media_index
            icon: icon-images

forms:
    label: duo_form.menu.forms
    icon: icon-clipboard
    children:
        forms:
            label: duo_form.menu.forms
            route: duo_form_listing_form_index
            icon: icon-paste
        submissions:
            label: duo_form.menu.submissions
            route: duo_form_listing_submission_index
            icon: icon-drawer

security:
    label: duo_security.menu.security
    icon: icon-shield
    children:
        users:
            label: duo_security.menu.users
            route: duo_security_listing_user_index
            icon: icon-user
        groups:
            label: duo_security.menu.groups
            route: duo_security_listing_group_index
            icon: icon-users
        roles:
            label: duo_security.menu.roles
            route: duo_security_listing_role_index
            icon: icon-man-woman

modules:
    label: duo_taxonomy.menu.modules
    icon: icon-equalizer
    children:
        taxonomies:
            label: duo_taxonomy.menu.taxonomies
            route: duo_taxonomy_listing_taxonomy_index
            icon: icon-price-tags

seo:
    label: duo_seo.menu.seo
    icon: icon-search
    children:
        redirects:
            label: duo_seo.menu.redirects
            route: duo_seo_listing_redirect_index
            icon: icon-shuffle
        robots:
            label: duo_seo.menu.robots
            route: duo_seo_listing_robots_index
            icon: icon-bug

settings:
    label: duo_admin.menu.settings
    icon: icon-cogs
    children:
        translations:
            label: duo_translator.menu.translations
            route: duo_translator_listing_entry_index
            icon: icon-earth
