pages:

media:
    label: Media
    url: /admin/media

forms:

security:

modules:

seo:

settings:
    label: Settings
    children:
        translations:
            label: Translations
            url: /admin/setting/translation