parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\AdminBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Configuration}'

    Duo\AdminBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\AdminBundle\Helper\LocaleHelper:
        public: true
        calls:
            - [ setDefaultLocale, [ '%locale%' ]]

    Duo\AdminBundle\EventSubscriber\Behavior\TaxonomySubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\AdminBundle\Twig\LocaleTwigExtension:
        arguments:
            $locales: '%locales%'
        tags:
            - { name: twig.extension }