parameters:

services:
    Duo\AdminBundle\EventListener\Behavior\SortListener:
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: duo.sort.preSort, method: preSort }

    Duo\AdminBundle\EventListener\Behavior\VersionListener:
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: duo.version.preClone, method: preClone }
            - { name: kernel.event_listener, event: duo.version.onRevert, method: preRevert }

    Duo\AdminBundle\EventSubscriber\Behavior\BlameSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\AdminBundle\EventSubscriber\Behavior\SlugSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: 1 }

    Duo\AdminBundle\EventSubscriber\Behavior\SortSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\AdminBundle\EventSubscriber\Behavior\TaxonomySubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\AdminBundle\EventSubscriber\Behavior\TimeStampSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\AdminBundle\EventSubscriber\Behavior\TranslateSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\AdminBundle\EventSubscriber\Behavior\TreeSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\AdminBundle\EventSubscriber\Behavior\UrlSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: 0 }

    Duo\AdminBundle\EventSubscriber\Behavior\VersionSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\AdminBundle\Twig\TestTwigExtension:
        tags:
            - { name: twig.extension }

    Duo\AdminBundle\Twig\LocaleTwigExtension:
        arguments:
            $locales: '%locales%'
        tags:
            - { name: twig.extension }

    Duo\AdminBundle\Twig\MenuTwigExtension:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'
        tags:
            - { name: twig.extension }