parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\AdminBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Configuration}'

    Duo\AdminBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    duo.admin.locale_helper:
        class: Duo\AdminBundle\Helper\LocaleHelper
        public: true
        calls:
            - [ setDefaultLocale, [ '%locale%' ]]
            - [ setLocalesFromString, [ '%locales%' ]]

    duo.admin.menu_builder:
        class: Duo\AdminBundle\Menu\MenuBuilder
        public: true

    Duo\AdminBundle\EventListener\Listing\TranslateListener:
        arguments:
            $localeHelper: '@duo.admin.locale_helper'
        tags:
            - { name: kernel.event_listener, event: duo.event.listing.preAdd, method: preAdd }
            - { name: kernel.event_listener, event: duo.event.listing.preEdit, method: preEdit }

    Duo\AdminBundle\Twig\LocaleTwigExtension:
        arguments:
            $localeHelper: '@duo.admin.locale_helper'
        tags:
            - { name: twig.extension }

    Duo\AdminBundle\Routing\UrlLoader:
        arguments:
            $localeHelper: '@duo.admin.locale_helper'
        tags:
            - { name: routing.loader, priority: 0 }