services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\AdminBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Configuration}'

    Duo\AdminBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    duo.admin.breadcrumb_helper:
        class: Duo\AdminBundle\Helper\BreadcrumbHelper
        public: true

    duo.admin.locale_helper:
        class: Duo\AdminBundle\Helper\LocaleHelper
        public: true
        calls:
            - [ setDefaultLocale, [ '%locale%' ]]
            - [ setLocalesFromString, [ '%locales%' ]]

    duo.admin.mailer_helper:
        class: Duo\AdminBundle\Helper\MailerHelper
        arguments:
            $twig: '@twig'
            $emailFrom: '%mailer_from%'
            $dkimConfig: { keyFile: '%dkim_key_file%', domain: '%dkim_domain%', selector: '%dkim_selector%' }
        public: true

    duo.admin.menu_builder:
        class: Duo\AdminBundle\Menu\MenuBuilder
        public: true

    duo.admin.event_listener.locale_listener:
        class: Duo\AdminBundle\EventListener\LocaleListener
        arguments:
            $defaultLocale: '%locale%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -8 }

    duo.admin.event_listener.listing.translate_entity_listener:
        class: Duo\AdminBundle\EventListener\Listing\TranslateEntityListener
        arguments:
            $localeHelper: '@duo.admin.locale_helper'
        tags:
            - { name: kernel.event_listener, event: duo.event.listing.entity.preAdd, method: preAdd }
            - { name: kernel.event_listener, event: duo.event.listing.entity.preEdit, method: preEdit }

    Duo\AdminBundle\Twig\LocaleTwigExtension:
        arguments:
            $localeHelper: '@duo.admin.locale_helper'
        tags:
            - { name: twig.extension }

    duo.admin.routing.url_loader:
        class: Duo\AdminBundle\Routing\UrlLoader
        arguments:
            $localeHelper: '@duo.admin.locale_helper'
        tags:
            - { name: routing.loader, priority: 0 }