services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\AdminBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Configuration}'

    Duo\AdminBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\AdminBundle\Helper\LocaleHelper:
        calls:
            - [ setDefaultLocale, [ '%locale%' ]]
            - [ setLocalesFromString, [ '%locales%' ]]

    Duo\AdminBundle\Helper\MailerHelper:
        arguments:
            $twig: '@twig'
            $emailFrom: '%mailer_from%'
            $dkimConfig: { keyFile: '%dkim_key_file%', domain: '%dkim_domain%', selector: '%dkim_selector%' }

    Duo\AdminBundle\Tools\Menu\MenuBuilder:
        public: true

    Duo\AdminBundle\EventListener\LocaleListener:
        arguments:
            $defaultLocale: '%locale%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 16 }

    Duo\AdminBundle\EventListener\TranslateListener:
        tags:
            - { name: kernel.event_listener, event: duo.event.listing.entity.preCreate, method: preCreate }
            - { name: kernel.event_listener, event: duo.event.listing.entity.preUpdate, method: preUpdate }

    Duo\AdminBundle\Twig\LocaleTwigExtension:
        tags:
            - { name: twig.extension }

    duo.admin.routing.url_loader:
        class: Duo\AdminBundle\Routing\UrlLoader
        tags:
            - { name: routing.loader, priority: 0 }