parameters:

services:
    duo.listener.sort:
        class: Duo\AdminBundle\EventListener\Behavior\SortListener
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: duo.event.onSort, method: onSort }

    duo.listener.version:
        class: Duo\AdminBundle\EventListener\Behavior\VersionListener
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: duo.event.onClone, method: onClone }
            - { name: kernel.event_listener, event: duo.event.onRevert, method: onRevert }

    duo.subscriber.blame:
        class: Duo\AdminBundle\EventSubscriber\Behavior\BlameSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    duo.subscriber.slug:
        class: Duo\AdminBundle\EventSubscriber\Behavior\SlugSubscriber
        tags:
            - { name: doctrine.event_subscriber, priority: 16 }

    duo.subscriber.sort:
        class: Duo\AdminBundle\EventSubscriber\Behavior\SortSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    duo.subscriber.taxonomy:
        class: Duo\AdminBundle\EventSubscriber\Behavior\TaxonomySubscriber
        tags:
            - { name: doctrine.event_subscriber }

    duo.subscriber.timestamp:
        class: Duo\AdminBundle\EventSubscriber\Behavior\TimeStampSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    duo.subscriber.translate:
        class: Duo\AdminBundle\EventSubscriber\Behavior\TranslateSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    duo.subscriber.tree:
        class: Duo\AdminBundle\EventSubscriber\Behavior\TreeSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    duo.subscriber.url:
        class: Duo\AdminBundle\EventSubscriber\Behavior\UrlSubscriber
        tags:
            - { name: doctrine.event_subscriber, priority: 8 }

    duo.subscriber.version:
        class: Duo\AdminBundle\EventSubscriber\Behavior\VersionSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    duo.twig.test:
        class: Duo\AdminBundle\Twig\TestTwigExtension
        tags:
            - { name: twig.extension }

    duo.twig.locale:
        class: Duo\AdminBundle\Twig\LocaleTwigExtension
        arguments:
            $locales: '%locales%'
        tags:
            - { name: twig.extension }

    duo.twig.menu:
        class: Duo\AdminBundle\Twig\MenuTwigExtension
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'
        tags:
            - { name: twig.extension }