security:
    label: duo.security.menu.security
    children:
        users:
            label: duo.security.menu.users
            route: duo_security_listing_user_index
        groups:
            label: duo.security.menu.groups
            route: duo_security_listing_group_index
        roles:
            label: duo.security.menu.roles
            route: duo_security_listing_role_index