services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\SecurityBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests}'

    Duo\SecurityBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\SecurityBundle\EventSubscriber\UserSubscriber:
        arguments:
            $encoder: '@security.password_encoder'
            $validator: '@validator'
        tags:
            - { name: doctrine.event_subscriber }

    duo.security.entity.user:
        class: '%duo.security.entity.user_class%'

    Duo\SecurityBundle\Entity\UserInterface: '@duo.security.entity.user'
