parameters:
    duo.security.user_class: Duo\SecurityBundle\Entity\User

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\SecurityBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\SecurityBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\SecurityBundle\EventListener\UserListingListener:
        tags:
            - { name: kernel.event_listener, event: duo.event.listing.postEdit, method: postEdit }

    Duo\SecurityBundle\EventSubscriber\UserSubscriber:
        arguments:
            $encoder: '@security.password_encoder'
            $validator: '@validator'
        tags:
            - { name: doctrine.event_subscriber }

    duo.security.user:
        class: '%duo.security.user_class%'

    Duo\SecurityBundle\Entity\UserInterface: '@duo.security.user'