version: '3'

volumes:
  var:

services:
  app:
    build: .
    volumes:
      - .:/app
      - var:/app/var
    ports:
      - '8000:8000'
    depends_on:
      - mysql
    environment:
      DATABASE_URL: 'mysql://root:admin@mysql/app'
      MAILER_URL: 'smtp://maildev'
      MEMCACHED_URL: 'memcached://memcached'
      TZ: Europe/Amsterdam

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app
      TZ: Europe/Amsterdam
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  pma:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - '8888:80'
    links:
      - mysql
    environment:
      PMA_HOST: mysql

  memcached:
    image: memcached:1.5
    ports:
      - '11211:11211'

  mail:
    image: djfarrelly/maildev
    ports:
      - '1025:25'
      - '1080:80'
