services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\SeoBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests}'

    Duo\SeoBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\SeoBundle\Routing\RedirectLoader:
        tags:
            - { name: routing.loader, priority: 0 }