services:
    _defaults:
        public: false

    duo_seo.controller.sitemap:
        class: Duo\SeoBundle\Controller\SitemapController
        arguments:
            $localeHelper: '@duo_admin.helper.locale'
        public: true

    duo_seo.form.type.meta_robots_choice:
        class: Duo\SeoBundle\Form\Type\MetaRobotsChoiceType
        arguments:
            $translator: '@translator'
        tags:
            - { name: form.type }

    duo_seo.routing.redirect_loader:
        class: Duo\SeoBundle\Routing\RedirectLoader
        arguments:
            $manager: '@doctrine.orm.entity_manager'
        tags:
            - { name: routing.loader, priority: 0 }
