duo_form:
    resource: '@DuoFormBundle/Controller/'
    type: annotation
    prefix: /admin

duo_form_view:
    resource: '@DuoFormBundle/Controller/FormController.php'
    type: annotation
    prefix: /
