duo_form_listing_form:
    resource: '@DuoFormBundle/Controller/FormListingController.php'
    type: annotation
    prefix: /form

duo_form_autocomplete:
    resource: '@DuoFormBundle/Controller/FormAutoCompleteController.php'
    type: annotation
    prefix: /form/autocomplete