services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\FormBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\FormBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    duo.form.form_part_configurator:
        class: Duo\FormBundle\Configurator\FormPartConfigurator
        public: true

    duo.form.form.form_part_collection:
        class: Duo\FormBundle\Form\FormPartCollectionType
        arguments:
            $configurator: '@duo.form.form_part_configurator'
        tags:
            - { name: form.type }

    Duo\FormBundle\EventListener\MenuListener:
        tags:
            - { name: kernel.event_listener, event: duo.event.menu.preLoad, method: preLoad }