services:
    _defaults:
        public: false

    duo_form.configurator.form_part:
        class: Duo\FormBundle\Configurator\FormPartConfigurator
        arguments:
            $eventDispatcher: '@event_dispatcher'

    duo_form.controller.form:
        class: Duo\FormBundle\Controller\FormController
        arguments:
            $mailerHelper: '@duo_admin.helper.mailer'
        public: true

    duo_form.form.type.form_part_collection:
        class: Duo\FormBundle\Form\Type\FormPartCollectionType
        arguments:
            $configurator: '@duo_form.configurator.form_part'
        tags:
            - { name: form.type }
