services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\FormBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests}'

    Duo\FormBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\FormBundle\Form\Type\FormPartCollectionType:
        arguments:
            $configurator: '@Duo\FormBundle\Configurator\FormPartConfigurator'
        tags:
            - { name: form.type }