services:
    _defaults:
        public: false

    duo_form.configurator.form_part:
        class: Duo\FormBundle\Configurator\FormPartConfigurator
        arguments:
            $eventDispatcher: '@event_dispatcher'

    duo_form.controller.form:
        class: Duo\FormBundle\Controller\FormController
        arguments:
            $mailerHelper: '@duo_admin.helper.mailer'
        public: true

    duo_form.form.type.form_part_collection:
        class: Duo\FormBundle\Form\Type\FormPartCollectionType
        arguments:
            $configurator: '@duo_form.configurator.form_part'
        tags:
            - { name: form.type }

    duo_form.form.type.recaptcha:
        class: Duo\FormBundle\Form\Type\RecaptchaType
        arguments:
            $key: '%duo_form.recaptcha_key%'
        tags:
            - { name: form.type }

    duo_form.validator.recaptcha:
        class: Duo\FormBundle\Validator\Constraints\RecaptchaValidator
        arguments:
            $secret: '%duo_form.recaptcha_secret%'
        tags:
            - { name: validator.constraint_validator }
