duo_admin:
    resource: '@DuoAdminBundle/Resources/config/routing.yml'
    prefix: /admin

duo_security:
    resource: '@DuoSecurityBundle/Resources/config/routing.yml'
    prefix: /admin

duo_seo:
    resource: "@DuoSeoBundle/Resources/config/routing.yml"
    prefix: /

duo_url:
    resource: .
    type: url

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /