# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admin:
            entity:
                class: Duo\SecurityBundle\Entity\UserInterface

    encoders:
        admin:
            class: Duo\SecurityBundle\Entity\UserInterface
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: admin

            anonymous: ~

            form_login:
                login_path: duo_security_login
                check_path: duo_security_login
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
                remember_me: true

            logout:
                path: duo_security_logout
                target: /admin

            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week
                name: ADMIN_REMEMBER_ME
                path: /admin
                domain: ~
                #secure: true

            logout_on_user_change: true

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            logout_on_user_change: true

    access_control:
        - { path: ^/admin/(login|forgot-password|reset-password), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/form/view/\d+, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_CAN_VIEW:       ROLE_USER
        ROLE_CAN_EDIT:       ROLE_CAN_VIEW
        ROLE_CAN_DELETE:     ROLE_CAN_EDIT
        ROLE_CAN_PUBLISH:    ROLE_CAN_EDIT
        ROLE_ADMIN:          ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
