imports:
    - { resource: '@DuoMediaBundle/Resources/config/services.yml' }

# Liip Imagine Configuration #
liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: media/cache
    driver: imagick

    filter_sets:
        thumb:
            quality: 85
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail: { mode: outbound, allow_upscale: false }

        crop:
            quality: 85
            filters:
                auto_rotate: ~
                strip: ~

        listing_preview:
            quality: 85
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail: { size: [100, 100], mode: inset, allow_upscale: false }
