liip_imagine:
    filter_sets:
        duo_media_thumb:
            quality: 85
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail: { mode: outbound, allow_upscale: false }

        duo_media_crop:
            quality: 85
            filters:
                auto_rotate: ~
                strip: ~

        duo_media_preview:
            quality: 85
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail: { size: [100, 100], mode: inset, allow_upscale: false }
