duo_media_listing:
    resource: '@DuoMediaBundle/Controller/Listing/'
    type: annotation
    prefix: /admin

duo_media_upload:
    path: /media/upload
    methods: 'PUT'
    defaults:
        _controller: 'duo_media.controller.upload:uploadAction'
