services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\MediaBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\MediaBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\MediaBundle\Helper\UploadHelper:
        arguments:
            $relativeUploadPath: '%duo.media.relative_upload_path%'
            $absoluteUploadPath: '%duo.media.absolute_upload_path%'

    Duo\MediaBundle\EventListener\UploadFileListener:
        tags:
            - { name: kernel.event_listener, event: duo.event.listing.form.postCreate, method: postCreate }
            - { name: kernel.event_listener, event: duo.event.listing.form.postUpdate, method: postUpdate }

    Duo\MediaBundle\EventSubscriber\ImageCropSubscriber:
        tags:
            - { name: doctrine.event_subscriber }