duo_seo_listing_redirect:
    resource: '@DuoSeoBundle/Controller/RedirectListingController.php'
    type: annotation
    prefix: /seo/redirect

duo_seo_listing_robot:
    resource: '@DuoSeoBundle/Controller/RobotListingController.php'
    type: annotation
    prefix: /seo/robots