services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\CoreBundle\EventListener\DeleteListener:
        tags:
            - { name: kernel.event_listener, event: duo.core.event.delete, method: onDelete }
            - { name: kernel.event_listener, event: duo.core.event.undelete, method: onUndelete }

    Duo\CoreBundle\EventListener\RevisionListener:
        tags:
            - { name: kernel.event_listener, event: duo.core.event.revision.clone, method: onClone }
            - { name: kernel.event_listener, event: duo.core.event.revision.revert, method: onRevert }

    Duo\CoreBundle\EventSubscriber\PublishSubscriber:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\RevisionSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\DeleteSubscriber:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\SortSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\TimestampSubscriber:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\TranslateSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\TranslationSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\TreeSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\SlugSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: -8 }

    Duo\CoreBundle\EventSubscriber\UrlSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: -16 }