services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

#    Duo\CoreBundle\Controller\:
#        resource: '../../Controller'
#        public: true
#        tags: ['controller.service_arguments']

    Duo\CoreBundle\EventSubscriber\UuidSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\PublishSubscriber:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\RevisionSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\DraftSubscriber:
        tags:
        - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\DeleteSubscriber:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\SortSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\TimestampSubscriber:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\TranslateSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\TranslationSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\TreeSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\CoreBundle\EventSubscriber\SlugSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: -8 }

    Duo\CoreBundle\EventSubscriber\UrlSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: -16 }