services:
    _defaults:
        public: false

    duo_part.event_subscriber.part:
        class: Duo\PartBundle\EventSubscriber\PartSubscriber
        tags:
            - { name: doctrine.event_subscriber, priority: -64 }

    duo_part.event_subscriber.reference:
        class: Duo\PartBundle\EventSubscriber\ReferenceSubscriber
        tags:
            - { name: doctrine.event_subscriber, priority: -128 }
