imports:
    - { resource: '@AppBundle/Resources/config/parameters.yml' }
    - { resource: '@AppBundle/Resources/config/services.yml' }

# Doctrine Configuration #
doctrine:
    orm:
        resolve_target_entities:
            Duo\PageBundle\Entity\PageInterface: '%duo_page.entity_class%'
            Duo\PageBundle\Entity\PageTranslationInterface: '%duo_page.entity_translation_class%'
            Duo\SecurityBundle\Entity\UserInterface: '%duo_security.entity_class%'

        dql:
            string_functions:
                group_concat: DoctrineExtensions\Query\Mysql\GroupConcat

# Doctrine Migrations Configuration #
doctrine_migrations:
    dir_name: '%kernel.project_dir%/app/migrations'
    namespace: Duo\Migrations
    table_name: duo_migrations
    name: Duo Migrations

# Liip Imagine Configuration #
liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: '%duo_media.cache_prefix%'
    driver: imagick

# Mjml Configuration #
mjml:
    bin: '%kernel.project_dir%/node_modules/.bin/mjml'
    mimify: true

# Twig Configuration #
twig:
    globals:
        brand_name: '%brand_name%'
        google_analytics_id: '%google_analytics_id%'
        google_recaptcha_key: '%google_recaptcha_key%'

# Duo Admin Configuration #
duo_admin:
    locales: '%locales%'
    dkim_key_file: '%dkim_key_file%'
    dkim_domain: '%dkim_domain%'
    dkim_selector: '%dkim_selector%'

# Duo Form Configuration #
duo_form:
    recaptcha_key: '%google_recaptcha_key%'
    recaptcha_secret: '%google_recaptcha_secret%'

# Duo Media Configuration #
duo_media:
    relative_path: '/media'
    absolute_path: '%kernel.project_dir%/web/media'
    cache_prefix: 'media/cache'

# Duo Page Configuration #
duo_page:
    entity_class: AppBundle\Entity\Page
    entity_translation_class: AppBundle\Entity\PageTranslation

# Duo Security Configuration #
duo_security:
    entity_class: AppBundle\Entity\User
