parameters:
    duo.page.entity.page_class: AppBundle\Entity\Page
    duo.page.entity.page_translation_class: AppBundle\Entity\PageTranslation
    duo.security.entity.user_class: AppBundle\Entity\User
