services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\EventListener\PagePartConfiguratorListener:
        tags:
            - { name: kernel.event_listener, event: duo.event.page_part_configurator.preLoad, method: preLoad }