services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\NodeBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\NodeBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']