softmedia_admin_test:
    resource: '@SoftmediaAdminBundle/Controller/TestController.php'
    type: annotation
    prefix: /test

softmedia_admin_page:
    resource: '@SoftmediaAdminBundle/Controller/PageAdminController.php'
    type: annotation
    prefix: /page

softmedia_admin_taxonomy:
    resource: '@SoftmediaAdminBundle/Controller/TaxonomyAdminController.php'
    type: annotation
    prefix: /taxonomy