parameters:

services:
    Softmedia\AdminBundle\EventSubscriber\Behavior\BlameableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\CloneableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\SluggableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\SortableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\TaxonomySubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\TimeStampableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\TranslatableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\TreeableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\Twig\TwigTestExtension:
        tags:
            - { name: twig.extension }