parameters:

services:
    Softmedia\AdminBundle\EventListener\Behavior\VersionableListener:
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: softmedia_admin.versionable.postClone, method: postClone }

    Softmedia\AdminBundle\EventSubscriber\Behavior\BlameableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\SluggableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: 1 }

    Softmedia\AdminBundle\EventSubscriber\Behavior\SortableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\TaxonomySubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\TimeStampableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\TranslatableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\TreeableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\EventSubscriber\Behavior\UrlableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: 0 }

    Softmedia\AdminBundle\EventSubscriber\Behavior\VersionableSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Softmedia\AdminBundle\Twig\TestTwigExtension:
        tags:
            - { name: twig.extension }

    Softmedia\AdminBundle\Twig\LocaleTwigExtension:
        arguments:
            $locales: '%locales%'
        tags:
            - { name: twig.extension }

    Softmedia\AdminBundle\Twig\MenuTwigExtension:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'
        tags:
            - { name: twig.extension }