services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\TranslatorBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\TranslatorBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\TranslatorBundle\EventSubscriber\EntrySubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Duo\TranslatorBundle\Loader\DatabaseLoader:
        tags:
            - { name: translation.loader, alias: db, priority: 128 }