services:
    _defaults:
        public: false

    duo_translator.controller.reload:
        class: Duo\TranslatorBundle\Controller\ReloadController
        arguments:
            $kernel: '@kernel'
        public: true

    duo_translator.event_subscriber.entry:
        class: Duo\TranslatorBundle\EventSubscriber\EntrySubscriber
        tags:
            - { name: doctrine.event_subscriber }

    duo_translator.loader.database:
        class: Duo\TranslatorBundle\Loader\DatabaseLoader
        arguments:
            $manager: '@doctrine.orm.entity_manager'
        tags:
            - { name: translation.loader, alias: db, priority: 8 }
