services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\PagePartBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\PagePartBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    duo.page_part.configurator:
        class: Duo\PagePartBundle\Configurator\PagePartConfigurator
        public: true

    duo.form.page_part:
        class: Duo\PagePartBundle\Form\PagePartType
        arguments:
            $configurator: '@duo.page_part.configurator'
        tags:
            - { name: form.type }

    Duo\PagePartBundle\EventSubscriber\PagePartSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: 1024 }