services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\PagePartBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\PagePartBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\PagePartBundle\EventSubscriber\PagePartSubscriber:
        tags:
            - { name: doctrine.event_subscriber, priority: 1024 }