imports:
    - { resource: '@DuoPageBundle/Resources/config/parameters.yml' }
    - { resource: '@DuoPageBundle/Resources/config/services.yml' }

doctrine:
    orm:
        resolve_target_entities:
            Duo\PageBundle\Entity\PageInterface: '%duo.page.entity.page%'
            Duo\PageBundle\Entity\PageTranslationInterface: '%duo.page.entity.page_translation%'