duo_page_listing_page:
    resource: '@DuoPageBundle/Controller/PageListingController.php'
    type: annotation
    prefix: /page

duo_page_autocomplete:
    resource: '@DuoPageBundle/Controller/PageAutoCompleteController.php'
    type: annotation
    prefix: /page/autocomplete

duo_page_part_modal:
    resource: '@DuoPageBundle/Controller/PagePartModalController.php'
    type: annotation
    prefix: /page-part/modal

duo_page_tree:
    resource: '@DuoPageBundle/Controller/PageTreeController.php'
    type: annotation
    prefix: /page