services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\PageBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Configuration}'

    Duo\PageBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    duo.page.page_part_configurator:
        class: Duo\PageBundle\Configurator\PagePartConfigurator
        public: true

    duo.page.form.page_part_collection:
        class: Duo\PageBundle\Form\PagePartCollectionType
        arguments:
            $configurator: '@duo.page.page_part_configurator'
        tags:
            - { name: form.type }

    duo.page.entity.page:
        class: '%duo.page.entity.page%'

    Duo\PageBundle\Entity\PageInterface: '@duo.page.entity.page'

    duo.page.entity.page_translation:
        class: '%duo.page.entity.page_translation%'

    Duo\PageBundle\Entity\PageTranslationInterface: '@duo.page.entity.page_translation'