services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\PageBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests,Configuration}'

    Duo\PageBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Duo\PageBundle\Form\Type\PagePartCollectionType:
        arguments:
            $configurator: '@Duo\PageBundle\Configurator\PagePartConfigurator'
        tags:
            - { name: form.type }

    duo.page.entity.page:
        class: '%duo.page.entity.page_class%'

    Duo\PageBundle\Entity\PageInterface: '@duo.page.entity.page'

    duo.page.entity.page_translation:
        class: '%duo.page.entity.page_translation_class%'

    Duo\PageBundle\Entity\PageTranslationInterface: '@duo.page.entity.page_translation'
