services:
    _defaults:
        public: false

    Duo\PageBundle\Entity\PageInterface: '@duo_page.entity.page'
    Duo\PageBundle\Entity\PageTranslationInterface: '@duo_page.entity.page_translation'

    duo_page.configurator.page_part:
        class: Duo\PageBundle\Configurator\PagePartConfigurator
        arguments:
            $eventDispatcher: '@event_dispatcher'

    duo_page.entity.page:
        class: '%duo_page.entity_class%'

    duo_page.entity.page_translation:
        class: '%duo_page.entity_translation_class%'

    duo_page.form.type.page_part_collection:
        class: Duo\PageBundle\Form\Type\PagePartCollectionType
        arguments:
            $configurator: '@duo_page.configurator.page_part'
        tags:
            - { name: form.type }

    duo_page.twig_extension.breadcrumbs:
        class: Duo\PageBundle\Twig\BreadcrumbsExtension
        tags:
            - { name: twig.extension }

    duo_page.twig_extension.page:
        class: Duo\PageBundle\Twig\PageExtension
        arguments:
            $manager: '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }
