services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Duo\DraftBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Duo\DraftBundle\EventSubscriber\DraftSubscriber:
        tags:
            - { name: doctrine.event_subscriber }